name: Jellyseerr - Media Request Manager
version: 1.1.0
slug: jellyseerr
description: Jellyseerr is a free and open source software application for managing requests for your media library.
url: https://github.com/RFC1918-hub/Hassio-Add-ons
webui: "http://[HOST]:[PORT:5055]"
startup: services
arch:
  - amd64
  - aarch64
init: false
map:
  - addon_config:rw
ports:
  5055/tcp: 5055
ports_description:
  5055/tcp: Jellyseerr web interface
environment:
  TZ: "Africa/Johannesburg"
healthcheck:
  test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5055/api/v1/status"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s
